### ISSUE TITLE
How can I replace the default EULA text?

### ISSUE THREAD

**Issue by bob53050** [oleg-shilo/wixsharp#312] opened 2018-03-12 22:07 UTC
Hello Oleg,

Can you please let me know how I can replace the default EULA text from a RTF or similar file?

Thanks for your help,

Bob

**Comment by oleg-shilo** [comment] 2018-03-13 02:52
```c#
project.LicenceFile = @"AppFiles\License.rtf";
```

**Comment by bob53050** [comment] 2018-03-13 03:11
Thanks Oleg :)

**Comment by merijndejonge** [comment] 2022-01-17 20:45
When I do this I get an error that the license file (foo.rtf in my case) cannot be found. My license file is at the same location as the setup.cs file:

```
C:\Users\xxx\RiderProjects\WixSharpExample\WixSharpExample>dir
 Volume in drive C has no label.
 Volume Serial Number is C4BA-412C

 Directory of C:\Users\xxx\RiderProjects\WixSharpExample\WixSharpExample

17/01/2022  21:42    <DIR>          .
17/01/2022  21:42    <DIR>          ..
17/01/2022  20:35               169 foo.rtf
17/01/2022  19:53               722 packages.config
17/01/2022  21:36             1.825 setup.cs
17/01/2022  21:41             6.104 WixSharpExample.csproj

```

 I get the following error:

- C:\agent\_work\66\s\src\ext\UIExtension\wixlib\WelcomeEulaDlg.wxs(42) : error LGHT0103 : The system cannot find the file 'foo.rtf'. 

If I set SourceBaseDir to Environment.CurrentDirectory like what I've seen in the examples, I still get an error:

- C:\agent\_work\66\s\src\ext\UIExtension\wixlib\WelcomeEulaDlg.wxs(42) : error LGHT0103 : The system cannot find the file 'C:\Users\xxx\RiderProjects\WixSharpExample\WixSharpExample\bin\Debug\foo.rtf'.

If I then change the path to the license file to @"..\..\foo.rtf", I still get an error but now somewhere else in the process:

- 0>C:\agent\_work\66\s\src\ext\UIExtension\wixlib\WelcomeEulaDlg.wxs(42): Error LGHT0103 : The system cannot find the file 'C:\Users\xxx\RiderProjects\WixSharpExample\WixSharpExample\..\..\foo.rtf'.

Is there anything that I'm doing wrong?

**Comment by oleg-shilo** [comment] 2022-01-18 13:32
Something is not happening the way it is supposed to. :(
Reopening the issue. Reclassifying it as a bug.

In a mean time please use either absolute path (it works)

**Comment by oleg-shilo** [comment] 2022-01-19 08:48
Checked again and during my first test, it was a typo in the name so indeed the file could not be found.
But when I fixed the name all started working. Most likely in your case, the relative path is not resolved into the correct absolute path. I suggest you add this troubleshooting code to assist you with the investigation:

```C#
project.LicenceFile = "licence.rtf";

if (!System.IO.File.Exists(project.LicenceFile))
    Console.WriteLine($"ERROR!!!!!: {project.LicenceFile.PathGetFullPath()}");
```

**Comment by merijndejonge** [comment] 2022-01-19 09:13
Thanks for figuring this out. I'm building with msbuild, so it might be an issue with the msbuild templates which do not set a folder correctly. The issue occurs for almost every file that I use, so it is not specific for the licensefile.

**Comment by oleg-shilo** [comment] 2022-01-19 11:07
Then I suggest you enable detailed logging:
```C#
project.PreserveTempFiles = true;
```
it will emit wxs file with all paths being absolute so you can see where exactly it goes wrong.

**Comment by merijndejonge** [comment] 2022-01-26 15:57
Thanks @oleg-shilo . The issue is solved. I was building the installer project from within Jetbrains Rider IDE. It turns out that the build configuration that I used set the working directory to the output folder (i.e., bin/Release). After I changed that to the folder where my .csproj file is located, everything works just fine.
Thanks for helping me!

**Closed** 2022-01-27 06:20 UTC
Labels: question, investigation in progress

**Comment by oleg-shilo** [comment] 2022-01-27 07:05
I do like this approach for troubleshooting

_Pseudocode_
```c#
static void Main()
{
    Environment.CurrentDir = Assembly.GetExecutingAssembly().Locatioon.GeDir().PathCombine(@"..\..\");
    
    var project = new Project(...
}
```

**Comment by merijndejonge** [comment] 2022-01-27 10:59
Thanks for the tip!

Fixing a few typ's in your pseudo-code, I ended-up using this code: 

```csharp           
 // Change working directory to top-level folder (i.e., the folder that contains the .csproj file).
var assemblyFolder = System.Reflection.Assembly.GetExecutingAssembly().Location.PathGetDirName();
Environment.CurrentDirectory = assemblyFolder.PathCombine($@"..{Path.DirectorySeparatorChar}..{Path.DirectorySeparatorChar}");
```
