### ISSUE TITLE
WixSharp Managed Setup - Custom UI - FeaturesDialog does not propagate user selection

### ISSUE THREAD

**Issue by talapoin** [oleg-shilo/wixsharp#784] opened 2019-12-12 09:38 UTC
Hi, 
I built an installer using custom ui project template and I noticed that if features are included selection done in featuresdialog is not respected. Installer always installs all folders/files. It does not respected features selected by user.

Test code is pretty simple.
```
var feature1 = new Feature("feature1");
var feature2 = new Feature("feature2");
var project = new ManagedProject("Path Visualizer",
                new Dir("%ProgramFiles%\Test",
                    new Dir(feature1, "feature1"),
                    new Dir(feature2, "feature2")));
```

This will always install both folders. Neverthless feature is selected or not.

I track the issue to [FeaturesDialog.cs](https://github.com/oleg-shilo/wixsharp/blob/master/Source/Templates/ProjectTemplates/WixSharp%20Managed%20Setup%20-%20Cusom%20UI/Dialogs/FeaturesDialog.cs)

void next_Click does comparision of **InitialUserSelectedItems** agains **InitialUserSelectedItems** which does not seem right in my opinion.

```
void next_Click(object sender, System.EventArgs e)
        {
            bool userChangedFeatures = InitialUserSelectedItems.Join(",") != InitialUserSelectedItems.Join(",");

            if (userChangedFeatures)
            {
                string itemsToInstall = features.Where(x => x.IsViewChecked())
                                                .Select(x => x.Name)
                                                .Join(",");

                string itemsToRemove = features.Where(x => !x.IsViewChecked())
                                               .Select(x => x.Name)
                                               .Join(",");

                if (itemsToRemove.Any())
                    Runtime.Session["REMOVE"] = itemsToRemove;

                if (itemsToInstall.Any())
                    Runtime.Session["ADDLOCAL"] = itemsToInstall;
            }
            else
            {
                Runtime.Session["REMOVE"] = "";
                Runtime.Session["ADDLOCAL"] = "";
            }

            SaveUserSelection();
            Shell.GoNext();
        }
```

In my project I change the method to this:
```
void next_Click(object sender, System.EventArgs e)
        {
            SaveUserSelection();
            bool userChangedFeatures = UserSelectedItems.Join(",") != InitialUserSelectedItems.Join(",");

            if (userChangedFeatures)
            {
                string itemsToInstall = features.Where(x => x.IsViewChecked())
                                                .Select(x => x.Name)
                                                .Join(",");

                string itemsToRemove = features.Where(x => !x.IsViewChecked())
                                               .Select(x => x.Name)
                                               .Join(",");

                if (itemsToRemove.Any())
                    Runtime.Session["REMOVE"] = itemsToRemove;

                if (itemsToInstall.Any())
                    Runtime.Session["ADDLOCAL"] = itemsToInstall;
            }
            else
            {
                Runtime.Session["REMOVE"] = "";
                Runtime.Session["ADDLOCAL"] = "";
            }

            Shell.GoNext();
        }
```
It started working after that. @oleg-shilo your opinion would be appreciated

[Test.zip](https://github.com/oleg-shilo/wixsharp/files/3954950/Test.zip)

**Comment by oleg-shilo** [comment] 2019-12-12 10:45
Sorry, but I don't see how the change you are proposing can make any difference on deployment outcome. Can you elaborate on the change.

This is my rationale. `SaveUserSelection` captures selected state of the features tree and saves it in the  
static string array `InitialUserSelectedItems`. This has affect on user experience as if this dialog is to be displayed again the tree will be initialized from its saved state. I do expect your change to break this user experience as you are now saving the state before it's changed by the user.

From the other hand the installation result because it is controlled via MSI session properties `REMOVE` and `ADDLOCAL`. And you are not changing processing these at all. Thus I don't see how the change in the behavior that you are observing can be caused by the code change you described.

**Comment by talapoin** [comment] 2019-12-12 10:59
well first of all the most important part is not moving SaveUserSelection to the top of the method. It's about changing the condition from

`bool userChangedFeatures = InitialUserSelectedItems.Join(",") != InitialUserSelectedItems.Join(",");`
to
`bool userChangedFeatures = UserSelectedItems.Join(",") != InitialUserSelectedItems.Join(",");`

original condition could never be **true** as it compares same array.

I moved SaveUserSelection to the top because UserSelectedItems are _NULL_ until you executed this method.

**Comment by oleg-shilo** [comment] 2019-12-12 11:05
Of course. I just missed the **real** change. Thank you.

The change can be simplified to 
```C#
bool userChangedFeatures = 
    UserSelectedItems?.Join(",") != InitialUserSelectedItems.Join(",");
```
And then `SaveUserSelection` may stay in it's original state.

Thank you. Will test and build a HotFix release in a day or so.

**Comment by talapoin** [comment] 2019-12-12 11:27
Thank you!

**Comment by oleg-shilo** [comment] 2020-02-04 10:48
In the next release you can use `session.InitFeaturesFromCurrentInstallation()`

**Closed** 2020-05-17 11:45 UTC
Labels: Done / Released, bug
