### ISSUE TITLE
Custom behavioral at CANCEL 

### ISSUE THREAD

**Issue by RachelXGanon** [oleg-shilo/wixsharp#1419] opened 2024-01-08 13:43 UTC
Hi, how can I run CA that would run on CANCEL/abort installation?
I'd like to a command in case of cancel/abort.
I can't use Exit Dialog, because I need it to support at quiet mode too.
Also, how can I detect it's on cancel mode?
Thanks.

**Comment by oleg-shilo** [comment] 2024-01-18 08:10
Excellent answer Richard. Thank you

**Comment by RachelXGanon** [comment] 2024-01-20 22:27
Indeed. Thank you @thenextman .

Thought I got another issue, sequencing the CA in 
```
When = When.Before,
Step = Step.InstallFiles
```

I get the files in the installation folder are not installed. And I need to use them in my CA.
Any idea how to sequence this, so it would rollback the After_Install and would be able to use the files?

Thank you!

**Comment by oleg-shilo** [comment] 2024-01-21 06:49
This is a questionable requirement.
You want to roll back your setup. Ok. This is an action that is normally performed when the setup fails to deploy your product artifacts. But in your case, you are expecting the artifacts to be present. 

I would encourage you to review your deployment strategy. If you are rolling back because the target environment is incompatible then you probably should not even let the setup start the session (use launch condition).

It's just a suggestion.

**Comment by RachelXGanon** [comment] 2024-01-21 09:20
Well, I install a file during the installation process and would like to uninstall it on rollback.
I need the artifacts to be present at the rollback so I could uninstall the file, and then of course they should be deleted.

The file I Install is an instrumentation manifest, the way to install it is by running the command:
 `wevtuil im <path to manifest>(manifest file is deployed to installation folder)`
 
In the rollback I'd like to uninstall it, and I cant do it without the file present.
The simplest way for me to cause to a rollback is by CANCEL which quite a basic requirement. 
Any idea how to schedule the CA?  Or do you another out of the box idea?

**Comment by oleg-shilo** [comment] 2024-01-21 10:59
Rollback is a transactional action of the MSI runtime. It removes ALL the files already deployed regardless if the setup already deployed all of them or only a part of of them. 

Rollback is performed not by the user but by MSI runtime. Thus if user deployed/created some files then it is user who needs to clear them. 

You can probably see how non-trivial your task is.

The problem is caused by the mixup of the _deployment_ and _configuration_. It is a very common problem/mistake with MSI authoring. Deploying the files in certain locations of the file system is _deployment_.  Configuring the system to use some deployment files in a certain way is _configuration_. _Configuration_ should always happen outside of _deployment_ even if both activities are done at the same time. 

A typical example of this: installing DBMS and configuring it (attach db files, adding users).

This is what good deployment practices are. At some point, Microsoft even rejected the product for "Design for Windows" if the validation detects that _deployment_ and _configuration_ are mixed.

Anyway, you can easily solve your problem this way:

- Install your product files. In this case, let MSI just delpoy the files in the right locations. This is your deployment.
- After the install do the configuration: in, `AfterInstall` register your manifest with wevtuil 
- In `OnLoad` check if you are uninstalling and if you are then unregister your manifest with wevtuil. And the MSI runtime will do the rest.

**Comment by RachelXGanon** [comment] 2024-01-21 11:05
I really do appreciate your response, Oleg. 
You explained it well.
I do exactly the way you suggested,
(well, more less.. I check at After_Install for both installation and uninstallation and register accordingly)

But it doesn't work for CANCEL.

**Comment by oleg-shilo** [comment] 2024-01-21 11:14
Great.
Then the actual challenge for you is to detect cancelation and not to register the manifest. 
Pseudo code:

```C#
void After_Install(Args e)
{
    if (e.IsInstalling || e.IsUpgrading)
    {
        if (File.Exists(e.InstallDir.PathCombine("my.manifest")))
            register_manifest();
    }
}
```

**Comment by RachelXGanon** [comment] 2024-01-21 11:19
Right exactly. Detect cancellation.
This is exactly my code as yours, but user can cancel the installation after the action `AfterInstall` was called.

![image](https://github.com/oleg-shilo/wixsharp/assets/89771659/5567468d-8a49-4a2b-aec2-18b6c9955093)

And then I'm being left with installed filed and no product.

**Comment by oleg-shilo** [comment] 2024-01-21 11:25
Hm, how user can cancel it?
This is my understanding that AfterInstall is called after the session is done. Am I missing something?

**Comment by oleg-shilo** [comment] 2024-01-21 11:29
Yep, you are right it's called before the end of the session:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/21dce9ae-e117-49bc-8648-4eb1d2f18c49)

**Comment by oleg-shilo** [comment] 2024-01-21 11:34
I will need to think how to provide some work around for this. 

But for you, then you can use an alternative trigger for the manifest registration. Not the `AfterInstall` but a closing the `ExitDialog` . Meaning that you will need to use ManagedUI.

At the moment I cannot offer you any better trigger. But I will investigate it further.

**Comment by RachelXGanon** [comment] 2024-01-21 11:42
Ok, thank you. 
`ExitDialog` is a cool idea but most of our users are using silent install. So, it's not going to work for me.

**Comment by oleg-shilo** [comment] 2024-01-21 11:45
According to this guide https://learn.microsoft.com/en-us/windows/win32/msi/adding-a-control-event-at-the-end-of-the-installation-to-run-launch
it needs to be done from the ExitDialog. As I suggested. Though I would prefer managed dialog instead of the native.

If you wouldn't use UI at all (only progress dialog) then AfterInstall event will be just fine. It is scheduled after `InstallFiles` action.

Unfortunately, the default MSI UI shows the enabled `cancel` button even after  `InstallFiles` action has finished.

**Comment by oleg-shilo** [comment] 2024-01-21 11:46
>  users are using silent install. 

Then they cannot cancel it after `AfterInstall` is fired. So you are good.

**Comment by RachelXGanon** [comment] 2024-01-21 12:01
Ok, cool.  I'll use `ExitDIalog`.
Any idea how can I detect Cancel at the exit dialog?
Also, this suppose to work at upgrade too, right?

**Comment by oleg-shilo** [comment] 2024-01-21 12:12
>Any idea how can I detect Cancel at the exit dialog?
Create your UI from VS2022 "CustomUI" and you will have access to all dialogs source code. Then just add your check to the cancel button OnClick event.

> Also, this suppose to work at upgrade too, right?
Yes

**Closed** 2024-03-04 10:37 UTC
Labels: enhancement, discussion
