### ISSUE TITLE
SequentialGuid duplication values

### ISSUE THREAD

**Issue by kain64** [oleg-shilo/wixsharp#266] opened 2018-01-17 08:11 UTC
Hi ,
I got wix errors on duplicated guids.  
example:
`S:\src\cpp\Misc\MSISetup\WixFullSetup\bin\Debug\DaletFull.wxs (2 hits)
	Line **5401**:               <Component Id="Component.NXToBigxx.xsl" Guid="85540ce8-957a-4756-0000-00003c234d7b" Win64="yes">
	Line **279965**:                     <Component Id="Component._...sdk_organizations_1.11.115.jar.45" Guid="85540ce8-957a-4756-0000-00003c234d7b" Win64="yes">`
I wantto fix it but I did not understand idea of SequentialGuid. can you please answer:
why did not use random GUID?
why need Sequential values?
what do you think if add configuration for guid configuration?

**Comment by oleg-shilo** [comment] 2018-01-18 08:03
Random GUID was the very first id allocation algorithm that WixSharp used. It has problems as many users prefer to hav deterministic reproducible IDs (e.g. for storing xml under source control).

Why don't you provide a sample that illustrates the problem an we can try to fix it.

You can also switch to a new id allocation algorithm that shows much better reliance for id duplication 
```C#
static public void Main(string[] args)
{
    Compiler.AutoGeneration.LegacyDefaultIdAlgorithm = false; // will be the default in the next release
    var project = ...
```

And you can always completely overwrite the algorithm:
```C#
static public void Main(string[] args)
{
    var project = ...

    project.CustomIdAlgorithm = (WixEntity entity) =>
    {
        if (entity is File) 
            return Guid.NewGuid().ToString();
        else
            return null; // pass to default ID generator
    };
```

**Comment by kain64** [comment] 2018-01-18 09:38
Hello, thank you .  
Issue reproduced only on huge setups : ~2GB of small files(jars/dlls 90% less than 1mb)
I used and now it work. 

```
 WixGuid.Generator = (seed) =>
            {
                return Guid.NewGuid();
            };
```
I will check code from yours answer.

**Comment by oleg-shilo** [comment] 2018-01-18 13:01
>  ~2GB of small files

It makes sense. Since you have enormous amount of files any hash may fail to be unique. 

Anyway, can you please confirm that the following code works (or doesn't):
```C#
static public void Main(string[] args)
{
    Compiler.AutoGeneration.LegacyDefaultIdAlgorithm = false; 
    var project = ...
```

**Comment by kain64** [comment] 2018-01-23 10:08
Hi
 Compiler.AutoGeneration.LegacyDefaultIdAlgorithm = false;
works.
but:  HashedTargetPathIdAlgorithm. 
https://github.com/oleg-shilo/wixsharp/blob/0fc5887f9b491d6ebd646942211a672081bea75d/Source/src/WixSharp/Project.cs#L920
looks dangerous for huge setups . 
random guid works for me:
WixGuid.Generator = (seed) =>
            {
                return Guid.NewGuid();
            };
I think need to close this ticket. now I have 2 workarounds for not usual setup.
Thank you for answers!

**Comment by oleg-shilo** [comment] 2018-01-23 11:12
Yes, any hash (as well as GUID) is not warranted to be unique. The chances for GUID to be unique are not 100% but very high. And for the hash the chances are definitely less though still high. After all .NET used hashes for objects identities (though with the warning).

I have updated the API documentation to warn the used about potential duplication:

![image](https://user-images.githubusercontent.com/16729806/35272733-5f6ca83a-008a-11e8-8a50-fdab0af92125.png)

I am closing the issue...

**Closed by oleg-shilo** 2018-01-23 11:12 UTC
Labels: question
