### ISSUE TITLE
How does one adjust the default value of a new key?

### ISSUE THREAD

**Issue by RobinCollie** [oleg-shilo/wixsharp#1253] opened 2023-01-10 13:16 UTC
Eerything I've tried has bounced back with "Sequence contains no elements":

new RegKey(fullSetup, RegistryHive.ClassesRoot, "testing",
    new RegValue("", "This is the default value"),
    new RegValue("commandLine:", "this is something else")),

**Comment by oleg-shilo** [comment] 2023-01-10 13:46
The problem is caused by the use of the column character in the regvalue name.
Even though this character is allowed by the registry, it interferes with WixSharp id auto-id allocation.

If it was a type in the name then it's easy to fix. But if it is intentional then you need to inject that column character in WSX just before the build in the pre-build event.

Anyway, it is a limitation of the current id allocation algorithm so it will be addressed in the very next release.

**Comment by RobinCollie** [comment] 2023-01-10 13:48
Ah, OK. So there is no other way to set the default value for a registry key until the bug is fixed?

**Comment by oleg-shilo** [comment] 2023-01-10 13:53
You misunderstood, it has nothing to do with the default value. Your problem is caused by the accidental `:` character at the end of the name in the second RegValue.

If you change the code this way it will build:

```C#
new RegKey(fullSetup, RegistryHive.ClassesRoot, "testing",
    new RegValue("", "This is the default value"),
        new RegValue("commandLine:", "this is something else")),
```

If it is creating (or not) a default value I am not sure. You will need to test it. The msi is built, WiX does not complain so mots likely it does what you want it to do.

**Comment by oleg-shilo** [comment] 2023-01-10 13:55
Too late for me. It's 1am :)

**Comment by RobinCollie** [comment] 2023-01-10 13:57
Oooof. That was me last night/this morning - hence I need a coffee IV to keep my eyes going. 

Get some rest.

**Closed** 2023-07-22 11:06 UTC
Labels: question
