### ISSUE TITLE
Access selected features in a custom action

### ISSUE THREAD

**Issue by cocowalla** [oleg-shilo/wixsharp#737] opened 2019-10-11 21:54 UTC
I'm using `ManagedProject`, and have an `AfterInstall` handler to "do stuff" after files are installed. As part of that custom action, I need to conditionally do things based on the installed features.

However, in the `AfterInstall` handler, using `e.Session.IsFeatureEnabled("My Feature")` always returns `false`, and attempting to access `e.Session.Features` results in an exception. `e.Session.Property("ADDLOCAL")` is always empty, even if I add it to `project.DefaultDeferredProperties`. I also don't see anything related to features in `e.Session.CustomActionData` or `e.Data`.

Is there any way to access the list of selected features in an `AfterInstall` handler when using a `ManagedProject`?

**Comment by oleg-shilo** [comment] 2019-10-12 12:33
Unfortunately MSI support for features is quite messy.

You guessed right. You do need to tunnel the property of interest (e.g. `ADDLOCAL`) to your `AfterInstall`. But the problem is that by default `DDLOCAL` is empty. 

This is the initialization code from FeaturesDialog:

```C#
void BuildFeaturesHierarchy()
{
    // MessageBox.Show(Runtime.Session.Property("ADDLOCAL"));
    features = Runtime.Session.Features;

    //build the hierarchy tree
    var rootItems = features.Where(x => x.ParentName.IsEmpty())
                            .OrderBy(x => x.RawDisplay)
                            .ToArray();
   . . .
```
If you uncomment `// MessageBox...` you will discover that at runtime `ADDLOCAL` is empty but `Runtime.Session.Features` is not. 

My conclusion from that is that MSI uses `ADDLOCAL` to overwrite the list of features but not to discover it. For discovery one has to use the session object.

It explains why your `ADDLOCAL` is always empty.

If you are running ManagedUI it sets `ADDLOCAL` at the end of FeaturesDialog. However if you do not use ManegedUI then you need to tunnel the features to the `AfetrInstall` by yourself:

```C#
static void project_BeforeInstall(SetupEventArgs e)
{
    e.Data["features"] = e.Session.Features
                                  .Where(x => x.RequestState != InstallState.Absent)
                                  .Select(x => x.Name)
                                  .Join(",");
    . . .

static void project_AfterInstall(SetupEventArgs e)
{
    MessageBox.Show(e.Session.GetMainWindow(),
                    "features = " + e.Data["features"] . . .
    
```

**Comment by cocowalla** [comment] 2019-10-12 14:22
I am using ManagedUI, but I think I see the problem now - `ADDLOCAL` is only being set if I use a "custom" install (which displays the feature tree). If I select a "typical" or "custom" install, then it's not set.

I can work around this by customising the `SetupTypeDialog`, but I wonder if there is a possibility to do this with the standard ManagedUI SetupTypeDialog in future?

**Comment by oleg-shilo** [comment] 2019-10-12 21:45
> I am using ManagedUI, but I think I see the problem now - ADDLOCAL 

Yes, this is what I meant "If you are running ManagedUI it sets ADDLOCAL at the end of FeaturesDialog."

Of course I can set it in WixSharp own `OnLoad`. But I am not so sure about it. MSI uses `ADDLOCAL` strictly to control **deviations** from the default enable/disable state of the features. But not to capture their state. Not the state but the modification of the state, 

And this is what FeatureTree dialog does. It modifies the defaults state of the of the features. Thus it is not WixSharp place to tweak with this property unless it modifies the features. Particularly because this property is always evaluated by MSI in combination with other [12 feature related properties](https://docs.microsoft.com/en-us/windows/win32/msi/addlocal).

However I see no risk in adding (and setting in OnLoad) something like `ADDFEATURES` that is pure WixSharp specific and indicates what features will be installed. As opposite to how the feature will be installed - that is `ADDLOCAL` for.

Is this something that you are looking for?

**Comment by cocowalla** [comment] 2019-10-12 21:51
Yes, something along those lines.

In my case I was able to work around this by using a custom `SetupTypeDialog` that does this when the "Typical" option is selected (it's the same as a "Complete" install in my particular case:

```c#
// Enable all features (stored in the `ADDLOCAL` property)
string itemsToInstall = this.Runtime.Session.Features
    .Select(x => x.Name)
    .Join(",");

this.Runtime.Session["ADDLOCAL"] = itemsToInstall;
```

But I take your point that to be _strict_ it might be better to not mess with `ADDLOCAL` at this stage. It just feels a bit weird to me in custom actions to have `ADDLOCAL` empty, and have that mean "the defaults", especially since I can use a "custom" install, leave everything at the defaults, and that _does_ change `ADDLOCAL`.

**Comment by oleg-shilo** [comment] 2019-10-13 14:36
I am changing this issue to a _Enhancement_. Will implement:
- ADDFEATURESproperty to always list all features to be installed
- Change the FeaturesDialog workflow and avoid updating `ADDLOCAL` if user  has not changed any features.

**Closed** 2019-12-20 14:05 UTC
Labels: bug, enhancement, question
