### ISSUE TITLE
Error 2911 not signaled in user interface.

### ISSUE THREAD

**Issue by monty241** [oleg-shilo/wixsharp#150] opened 2017-09-03 21:41 UTC
When running a MSI installer created with wixsharp 1.4.7.2, the log file lists (great that it is easy to open):

ActionData: File: C:\Config.Msi\1921d4a6.rbf
Info: DEBUG: Error 2911:  Could not remove the folder C:\Config.Msi\.
Info: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2911. 
CommonData: Message type: 2, Argument: 1

And ultimately:

Info: Action ended 23:36:37: INSTALL. Return value 1.

But the default dialog does not indicate that anything went wrong. See picture.

![image](https://user-images.githubusercontent.com/7579444/30006785-129916e0-9101-11e7-870a-fdd2027f53a7.png)

That is confusing.

I think it would improve the user experience and reduce confusion when this error would be signaled directly in the dialog.

The problem can only be seen when you carefully check programs & features, or do view log.

That there is an error 2911 is not an issue; when I set property REINSTALL to ALL and REINSTALLMODE to amus, it seems to trigger this problem.

[Invantive Build Tool.txt](https://github.com/oleg-shilo/wixsharp/files/1273273/Invantive.Build.Tool.txt)

**Comment by oleg-shilo** [comment] 2017-09-09 13:24
Valid point. 
Fixed with 7f89b4daaaabbf28fadadcb8fa2bd807f750421b. Now the title reflact the fact that the install hs finished with the error.

**Comment by monty241** [comment] 2017-09-09 13:58
Thanks!

**Closed** 2017-11-13 22:20 UTC
Labels: bug, Done

**Comment by NickeManarin** [comment] 2019-04-10 02:21
I'm still triggering this issue with the error 2911. Could you explain more about that?

**Comment by NickeManarin** [comment] 2019-04-10 02:23
Also, how can I add the error dialog? I'm using a custom UI:

```
            project.ManagedUI.InstallDialogs.Add<WelcomeDialog>()
                                            .Add<InstallDirDialog>()
                                            .Add<ProgressDialog>()
                                            .Add<ExitDialog>();

            project.ManagedUI.ModifyDialogs.Add<MaintenanceTypeDialog>()
                                           .Add<ProgressDialog>()
                                           .Add<ExitDialog>();
```

**Comment by oleg-shilo** [comment] 2019-04-10 12:46
Sorry, I cannot. :)
The defect was correctly raised about the exit dialog not reflecting the fact that the setup has encountered the error. And this very defect was fixed. 

But the fact that error 2911 has occurred is not a subject of this report.
@monty241 wrote "That there is an error 2911 is not an issue;"

In fact error 2911 is not associated with WixSharp itself but most likely related to the deployment logic of your project. You will need to lookup for that on WiX/MSI resources. However if you find that the cause is relataed to the WixSharp functionality please report it here.

**Comment by NickeManarin** [comment] 2019-04-10 19:31
Fair. :) 
I'm going to recheck every line of code to see if I'm able to find any issues with my code. If I'm not able to find any problems, I'll open another issue ticket.

**Comment by RachelXGanon** [comment] 2022-07-24 12:27
Did you find something regarding this?
