### ISSUE TITLE
Merge Modules cause NullRefException when MediaTemplate is used

### ISSUE THREAD

**Issue by dguder** [oleg-shilo/wixsharp#362] opened 2018-05-09 15:23 UTC
Hi, 
I'm using media template and when I add a merge module a `NullReferenceException` occur at `WixSharp.Compiler.ProcessMergeModules`

From your sample, this will cause the exception:
```csharp
var project =
        new Project("MyMergeModuleSetup",
            new MediaTemplate { CompressionLevel = CompressionLevel.none, EmbedCab = false }, 
            new Dir(@"%ProgramFiles%\My Company",
                new File(featureA, @"Files\MainFile.txt"),
                new Merge(featureB, @"Files\MyMergeModule.msm"),
                new Merge(featureB, @"Files\MyMergeModule1.msm")
                ),
            new EnvironmentVariable("foo", "bar"));

//must be cleared to work with MediaTemplate
project.Media.Clear();
```
but this is working.
```csharp
var project =
        new Project("MyMergeModuleSetup",
            new MediaTemplate { CompressionLevel = CompressionLevel.none, EmbedCab = false }, 
            new Dir(@"%ProgramFiles%\My Company",
                new File(featureA, @"Files\MainFile.txt")
                //new Merge(featureB, @"Files\MyMergeModule.msm"),
                //new Merge(featureB, @"Files\MyMergeModule1.msm")
                ),
            new EnvironmentVariable("foo", "bar"));

//must be cleared to work with MediaTemplate
project.Media.Clear();
```
The exception could be avoided when diskId is set to "1" when no Media attribute was found. But I'm not sure how it should be defined within WiX itself.

**Comment by oleg-shilo** [comment] 2018-05-10 03:25
Thank you for reporting this.

The problem with the null ref is fixed now - simple C# mistake. However... 

it looks like there is a conflict between the branches of the WiX API. 
This is what candle demands when the `DiskId` is not specified:
```txt
error CNDL0049 : The Merge/@DiskId attribute was not found or empty; 
It is required, or it can be specified in the parent Directory element.
```

And yet the documentation clearly indicates that this attribute is optional:

![image](https://user-images.githubusercontent.com/16729806/39850180-497ee296-5453-11e8-9ff9-9378c36b2952.png)

And the problem is that the `media` element is not available in case of `MediaTemplate` approach. Meaning that the `Media.Diskid` cannot be discovered. 

If you ask me it is a clear WiX API bug. 

As a work around I implemented setting the `DiskId` to "1" without any confidence in this approach as it is a WiX problem and only them can truly solve it.

If you need to use an alternative value you will need to overtire this attribute in the post-generation event:

```C#
project.WixSourceGenerated += 
    doc => doc.Root.Descendants("Merge")
              .ForEach(x => x.SetAttribute("DiskId", "<something else>"));

```

**Comment by dguder** [comment] 2018-05-14 09:00
Thx. 
I digged into the WiX code but I'm need some more time to find the way how to describe the issue for WiX toolset.

**Closed** 2018-07-15 13:47 UTC
Labels: Done: waiting for release, bug
