### ISSUE TITLE
Empty directory belonging to a feature causes an error

### ISSUE THREAD

**Issue by apawsey** [oleg-shilo/wixsharp#279] opened 2018-01-28 22:09 UTC
Hi,

I want to create an empty directory for our log files in the ProgramData folder.  I first added the directory like this:
```
Project project = new Project("TaxPacc",
                new LaunchCondition("CUSTOM_UI=\"true\" OR REMOVE=\"ALL\"", "Please run setup.exe instead."),
                new Dir(@"%ProgramFiles%\TaxPacc",
                    new Dir("Server",
                        new DirFiles(serverFeature, $@"..\TaxPacc.Service.Web\bin\{buildPath}\net461\win8-x86\*.*",
                            FileExclusions))),
                new Dir(@"%CommonAppDataFolder%\TaxPacc\Server",
                    new DirPermission("[SERVICEACCOUNTUSERNAME]", "[SERVICEACCOUNTDOMAIN]", GenericPermission.All)),
```
And didn't get any errors, except I realised that a new automatic feature called "Complete" was added just for this directory, which is fair enough.

So then I tried to make sure it got included with the "Server" feature, by changing the one line to...
 ```
new Dir(serverFeature, @"%CommonAppDataFolder%\TaxPacc\Server",
                    new DirPermission("[SERVICEACCOUNTUSERNAME]", "[SERVICEACCOUNTDOMAIN]", GenericPermission.All)),
```
But now I get an error in the msi log like this...
```
Action start 23:27:59: CostFinalize.
DEBUG: Error 2711:  The specified Feature name ('Server') not found in Feature Table.
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: Server, , 
MSI (s) (84:FC) [23:28:00:117]: Product: TaxPacc -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2711. The arguments are: Server, , 
```

I compared the wxs files generated and found a slight difference.  With the empty directory not added to the feature, I got this in the wxs:
```
<Directory Id="CommonAppDataFolder" Name="CommonAppDataFolder">
        <Directory Id="CommonAppDataFolder.TaxPacc" Name="TaxPacc">
          <Directory Id="CommonAppDataFolder.TaxPacc.Server" Name="Server">

            <Component Id="ComponentDirPermission" Guid="5aff9669-175c-4bec-b4b7-dd2e4fc36d88" KeyPath="yes">
              <CreateFolder>
                <PermissionEx User="[SERVICEACCOUNTUSERNAME]" Domain="[SERVICEACCOUNTDOMAIN]" GenericAll="yes" xmlns="http://schemas.microsoft.com/wix/UtilExtension" />
              </CreateFolder>
              <RemoveFolder Id="CommonAppDataFolder.TaxPacc.Server" On="uninstall" />
            </Component>

          </Directory>
        </Directory>
      </Directory>
```

But with it added to the feature I got this:
```
<Directory Id="CommonAppDataFolder" Name="CommonAppDataFolder">
        <Directory Id="CommonAppDataFolder.TaxPacc" Name="TaxPacc">
          <Directory Id="CommonAppDataFolder.TaxPacc.Server" Name="Server">

            <Component Id="Component.Server" Guid="7f954663-c67e-48c6-a525-cfea6f70581b" KeyPath="yes">
              <CreateFolder />
              <RemoveFolder Id="CommonAppDataFolder.TaxPacc.Server" On="uninstall" />
            </Component>

            <Component Id="ComponentDirPermission" Guid="7f954663-c67e-48c6-a525-cfea43519964" KeyPath="yes">
              <CreateFolder>
                <PermissionEx User="[SERVICEACCOUNTUSERNAME]" Domain="[SERVICEACCOUNTDOMAIN]" GenericAll="yes" xmlns="http://schemas.microsoft.com/wix/UtilExtension" />
              </CreateFolder>
            </Component>

          </Directory>
        </Directory>
      </Directory>
```

Also, and a bit more weirdly, my "Server" feature has an Id of "Server" when I don't add the empty directory to it, but when I add the empty directory, the feature's id is set to "Server_".

There is obviously a couple of other changes to the wxs, like the automatic "Complete" feature, and where components are referenced, but they all make sense. I just can't understand why it rename's the "Server" feature to "Server_" which then seems to cause the error.

**Comment by oleg-shilo** [comment] 2018-02-01 22:12
Hi Adam, this is not a trivial issue so it will take some time to investigate. 
Sorry for the delay.

**Comment by apawsey** [comment] 2018-02-01 22:16
No issue at all... I worked around it by including a small file I don't really need but its not a big issue.  Should probably also just note that the issue only occurs with an empty directory.  As soon as I put a file in there as with the workaround, it works fine. But obviously just thankful for the framework... delay's not an issue!! 😄

**Comment by oleg-shilo** [comment] 2018-02-15 13:58
Hi Adam,
Just wanted to see if the fix for this one can be pushed to the today release...
I cannot reproduce that bahavier. This is what I have used as a test-case:
```C#
var serverFeature = new Feature("Server");

Project project = new Project("TaxPacc",
        new LaunchCondition("CUSTOM_UI=\"true\" OR REMOVE=\"ALL\"", "Please run setup.exe instead."),
        new Dir(@"%ProgramFiles%\TaxPacc",
            new File("setup.cs")),
        new Dir(serverFeature, @"%CommonAppDataFolder%\TaxPacc\Server",
            new DirPermission("serviceaccountusername", "serviceaccountdomain", GenericPermission.All)));
project.PreserveTempFiles = true;
project.BuildMsi();
```
Can you please have a look and possibly provide a better test case.
Thank you.

**Comment by oleg-shilo** [comment] 2018-02-16 17:22
I am really glad you brought this problem to my attention. When I "dissected" it I found so may small things that can be improved so I just couldn't let them go unaddressed

I have committed the changes/fixes today but now let's review the all peculiar points of your challenge. 

-  _But now I get an error in the msi log like this..._
I cannot reproduce it so let's leave it there. Probably these were secondary symptoms caused by the actual problem. There were some minor problem with permission features being ignored and taken from parent dir instead (fixed now). Though in my test even without the fix your test case worked OK.  

- _I want to create an empty directory for our log files in the ProgramData folder._
I am not questioning your requirements but it does sound like a bit wrong approach. Any logger should be able to create the log folder if it does not exist. Leaving it for setup to do compromises reliability of the solution. Imagine what an accidental deletion of this folder would do to your application.

- _But with it added to the feature I got this:_
The way you encoded features is not ideal. The problem is that by having entities without features you have triggered creation of the implicit "Complete" feature. It is all good but with implicit Features you cannot effectively manage them. For example if you use explicit features you can enclose features into each other:
  ```C#
  var serverFeature = new Feature("Server");
  var completeFeature = new Feature("Complete");
  completeFeature.Add(serverFeature);
  ```
- I also discovered that the existing mechanism for associating entities with multiple features is not very convenient:
  ```C#
  new Dir(@"%CommonAppDataFolder%\TaxPacc\Server",
           new File(....))
  {
      Features = new Feature[] { completeFeature, serverFeature }
  }
  ```
  Thus I used this opportunity to improve the API by allowing a special `Feature` type that is a container for multiple `Feature` instances - `FeatureSet`. This way multiple features can be passed via the existing constructors:
  ```C#
  new Dir(new FeatureSet(completeFeature, serverFeature), 
          @"%CommonAppDataFolder%\TaxPacc\Server",
          new File(....))
  ```
- _I compared the wxs files generated and found a slight difference._
  The permissions items all have their components generated as usual. However when the feature is associated with the Dir an extra component (Dir component) is generated before permissions being processed. This may lead to a less attractive but still correctly functioning WXS. Thus unless it triggers the problem I wouldn't worry about that. 

- _I just can't understand why it rename's the "Server" feature to "Server_" which then seems to cause the error._
Appending '_' is the technique for ensuring uniqueness of IDs:
  ```C#
  while (alreadyTakenIds.Contains(entity.id)) //last line of defense against duplication
      entity.id += "_";
  ```
  Thus appearance of this suffix depends on the previous id allocations. So it is normal. However I have found a few unnecessarily over aggressive ID allocations in Dir implementation and simplified them. Thus for the sample below the generated Feature id is still "Server":  

  ```C#
  var serverFeature = new Feature("Server");
  
  var project = new Project("TaxPacc",
          new LaunchCondition("CUSTOM_UI=\"true\" OR REMOVE=\"ALL\"", "Please run setup.exe instead."),
          new Dir(@"%ProgramFiles%\TaxPacc",
              new File(completeFeature, "setup.cs")),
                  new Dir(serverFeature, @"%CommonAppDataFolder%\TaxPacc\Server",
                     new DirPermission("serviceaccountusername", "serviceaccountdomain", GenericPermission.All)));
  project.UI = WUI.WixUI_FeatureTree;
  project.BuildMsi();
```
  
Though, even before the change that 'Server_' didn't cause any problems.

**Closed** 2018-05-02 02:36 UTC
Labels: Done, bug
