### ISSUE TITLE
Changing the default install directory to anything other than ProgramFiles stops removing files on uninstall

### ISSUE THREAD

**Issue by alexgoaga** [oleg-shilo/wixsharp#378] opened 2018-05-28 16:45 UTC
Hi,

If I change the default install directory
var project =
                new Project("TestProd",

                    new Dir(@"**%LocalAppDataFolder%**\My Company\My Product",
                        new File(@"Files\Bin\MyApp.exe"),
                        new Dir(@"Docs\Manual",
                            new File(@"Files\Docs\Manual.txt")))); 

**%ProgramFiles% -> %LocalAppDataFolder%**
and then when msi is installed I change it again to something else, on uninstall the files are not removed.

var project =
                new Project("TestProd",
                    new Dir(@"%LocalAppDataFolder%\My Company\My Product",
                        new File(@"Files\Bin\MyApp.exe"),
                        new Dir(@"Docs\Manual",
                            new File(@"Files\Docs\Manual.txt")))
                    );

            project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
            project.UI = WUI.WixUI_InstallDir;

            project.OutDir = @"%LATEST_RELEASE%\MSI";
            project.SourceBaseDir = "%LATEST_RELEASE%";
            project.BuildMsi();
For the above project, if the install directory is changed at install time, the uninstall fails to remove the files

Thanks,
Alex.

**Comment by oleg-shilo** [comment] 2018-05-29 11:36
Have a look at "InstallDir_AbsolutePath" sample in [samples folder](https://github.com/oleg-shilo/wixsharp/tree/master/Source/src/WixSharp.Samples/Wix%23%20Samples).

**Comment by alexgoaga** [comment] 2018-05-29 22:40
Hi,

I have checked the sample, but I still see the issue. For instance, for the following code if I change the installation directory in 'InstallDirDlg' to something like '%AppDataFolder%\MyApp**11**' at install the message box displays the correct install path, but at uninstall the original path is being displayed '%AppDataFolder%\MyApp' and the files are not removed.

If I change %AppDataFolder% to %ProgramFiles% then it works

class Script
    {
        public static void Main(string[] args)
        {
            Environment.SetEnvironmentVariable("LATEST_RELEASE", Environment.CurrentDirectory);

            var project =
                new ManagedProject("TestProd",

                    new Dir(@"%AppDataFolder%\MyApp",
                        new File(@"Files\Bin\MyApp.exe"),
                        new Dir(@"Docs\Manual",
                            new File(@"Files\Docs\Manual.txt"))));
            project.AfterInstall += Project_AfterInstall;
            project.GUID = new Guid("6f330b47-2577-43ad-9095-1861ba25889b");
            project.UI = WUI.WixUI_InstallDir;

            project.OutDir = @"%LATEST_RELEASE%\MSI";
            project.SourceBaseDir = "%LATEST_RELEASE%";

            project.PreserveTempFiles = true;
            project.BuildMsi();
        }

        static void Project_AfterInstall(SetupEventArgs e)
        {
            MessageBox.Show("e.InstallDir -> " + e.InstallDir + "\n" +
                            "EnvVar('INSTALLDIR') -> " + Environment.GetEnvironmentVariable("INSTALLDIR"),
                "AfterInstall");
        }
    }

**Comment by oleg-shilo** [comment] 2018-05-30 11:48
WixSharp does not directly control neither installl nor uninstall algorithm. It only builds the WiX definition and compiles it into msi file. Quite possibly MSI/WiX handles `AppDataFolder` and `ProgramFilesFolder` differently.

Have a look at generated *.g.wxs files and see if its structure is identical (except installdir name) in both `AppDataFolder` and `ProgramFilesFolder` cases. If it is then it is MSI/WiX problem.

However if the strtucture is different then WixSharp wxs generation is inadequate and it will needs to be fixed.

**Comment by alexgoaga** [comment] 2018-06-01 22:47
Hi,

It looks like the generated files are different between AppDataFolder and ProgramFilesFolder.
I have attached the generated files.

Thanks,
Alex.


[GeneratedFiles.zip](https://github.com/oleg-shilo/wixsharp/files/2064373/GeneratedFiles.zip)

**Comment by oleg-shilo** [comment] 2018-06-02 07:57
Great. Let's review the test results.

The discrepancy you have is has a good reason to exist. Your have changed "ProgramFiles" (system wide dir) to "LocalAppData" (user specific dir). MSI does not like it and throws so called ICE validation error. 

```txt
...\My Product.wxs(12) : error LGHT0204 : ICE38: Component Component.setup.cs_1726297995 installs to user profile. It must use a registry key under HKCU as its KeyPath, not a file.
```
If you ask me, MS has no business to interfere with used deployment logic, but it does. 

In order to avoid this problem WixSharp injects dummy registry values that are to be installed to the user-profile so the msi can be compiled.  This is exactly what is causing the difference in the files you attached to your prev post.

You can disable that "dummy registry values" injection but the you will need to suppress the ICE error via global settings.   
```C#
AutoElements.DisableAutoUserProfileRegistry = true;
Compiler.LightOptions += " -sice:ICE38";
```
If you do that the discrepancy in the wxs files will practically disappear.

However... I have to question your testing. I just took a simple as possible setup definition, compiled. installed and uninstalled it. It worked prefectly: 
```C#
var project = 
        new Project("My Product",
            new Dir(@"%LocalAppData%/My Company/My Product",
                new File("setup.cs")));

project.PreserveTempFiles = true;
project.GUID = new Guid("6fe30b47-2577-43ad-9095-1861ba25889c");
project.BuildMsi(); 
```
I tested it with and without `AutoElements.DisableAutoUserProfileRegistry`. I have also tested the "InstallFiles" sample. All works as expected.

Thus I am not convinced the problem actually exists. I suggest you repeat my tests in your environment and verify your scenario again.

**Comment by alexgoaga** [comment] 2018-06-02 22:29
Hi,

To be able to replicate this issue, you need to change the path at install time from ''%LocalAppData%/My Company/My Product" to something like "%LocalAppData%/My Company/My Product111111111".
If the default path is not changed at install time, then the uninstall works as expected.

Also, adding 
            AutoElements.DisableAutoUserProfileRegistry = true;
            Compiler.LightOptions += " -sice:ICE38";
fixes the problem. 

Thank you for the suggestion,
Alex.

**Comment by alexgoaga** [comment] 2018-06-02 22:36
Also, adding DisableAutoUserProfileRegistry causes an error when trying to add a shortcut.
Is there a way to add a shortcut with this option?

Thanks,
Alex.

**Comment by oleg-shilo** [comment] 2018-06-03 01:18
> Also, adding DisableAutoUserProfileRegistry causes an error when trying to add a shortcut.

Sorry, I am afraid you missed the point. The problem is caused by MSI's over-restrictive validation policies not by WixSharp. And having `DisableAutoUserProfileRegistry = true` simply disables WixSharp built-in work around for bypassing this policies. Thus disabling this work around does not cause the problem but disables the "fix".

> Also, adding... fixes the problem.

Make no mistake, by having `Compiler.LightOptions += " -sice:ICE38";` you are effectively saying. I accept that it is an error but I want to hide and ignore it. Thus one cannot fix the problem by hiding it. The same applies to WixSharp. It's not fixing it but providing a work around that you decided to disable. That's why I always use "fix" in quotes.

> DisableAutoUserProfileRegistry causes an error when trying to add a shortcut.

Of course. the ICE restriction is causing problems for any setup that installs into the user-profile (e.g. prog-menu shortucts). 

I also list in the code documentation a few code samples that demonstrates the problem:

![image](https://user-images.githubusercontent.com/16729806/40882254-3afda7f0-671f-11e8-9c13-3e80e8692686.png)

**Comment by alexgoaga** [comment] 2018-06-03 10:43
Sorry for not being clear in the previous post, I do understand that this is an issue with MS generation.

By disabling the "dummy registry values", the installer works as expected when uninstalling, but brings some other issues as described above.

To fix this, I will not disable the registry files and add a custom action on uninstall to try and clean any files after uninstall.

Thank you for your help,
Alex.

**Comment by oleg-shilo** [comment] 2018-06-04 08:45
Great. Then we are on the same page. I will close this issue and you can reopen it if the need arises.

**Closed by oleg-shilo** 2018-06-04 08:45 UTC
Labels: question
