### ISSUE TITLE
Redirect to a custom dialog after CommonDialogs.BrowseDlg

### ISSUE THREAD

**Issue by vinil2001** [oleg-shilo/wixsharp#956] opened 2020-12-15 09:59 UTC
Hi,

It is possible to fired custom dialogs after CommonDialogs.BrowseDlg fired?

Now, after CommonDialogs.BrowseDlg, my installator skipping all next dialogs and starts installation process.

public static CustomUI BuildCustomUI()
        {
            portAndPassForm1 = new PortAndPassForm1();
            Dialog portAndPassDialog = portAndPassForm1.ToWDialog();

            startServiceParamsForm2 = new StartServiceParamsForm2();
            Dialog startServiceParamsDialog = startServiceParamsForm2.ToWDialog();

            var customUI = new CustomUI();

            customUI.CustomDialogs.Add(portAndPassDialog);
            customUI.CustomDialogs.Add(startServiceParamsDialog);

            customUI.On(NativeDialogs.ExitDialog, Buttons.Finish, new CloseDialog() { Order = 9999 });

            customUI.On(NativeDialogs.WelcomeDlg, Buttons.Next, new ShowDialog(NativeDialogs.InstallDirDlg));

            customUI.On(NativeDialogs.InstallDirDlg, Buttons.Back, new ShowDialog(NativeDialogs.WelcomeDlg));
            customUI.On(NativeDialogs.InstallDirDlg, Buttons.Next, new ShowDialog(portAndPassDialog));
            customUI.On(NativeDialogs.InstallDirDlg, Buttons.ChangeFolder,
                                                             new SetProperty("_BrowseProperty", "[WIXUI_INSTALLDIR]"),
                                                             new ShowDialog(CommonDialogs.BrowseDlg));

            customUI.On(CommonDialogs.BrowseDlg, Buttons.Cancel, new ShowDialog(NativeDialogs.InstallDirDlg));

            customUI.On(portAndPassDialog, Buttons.Back, new ShowDialog(NativeDialogs.InstallDirDlg));
            customUI.On(portAndPassDialog, Buttons.Next, new ShowDialog(startServiceParamsDialog));
            customUI.On(portAndPassDialog, Buttons.Cancel, new CloseDialog("Exit"));

            customUI.On(startServiceParamsDialog, Buttons.Back, new ShowDialog(portAndPassDialog));
            customUI.On(startServiceParamsDialog, Buttons.Next, new ShowDialog(NativeDialogs.VerifyReadyDlg));
            customUI.On(startServiceParamsDialog, Buttons.Cancel, new CloseDialog("Exit"));

            customUI.On(NativeDialogs.VerifyReadyDlg, Buttons.Back, new DialogAction { Name = "DoAction", Value = "RemoveSettings" },
                new ShowDialog(startServiceParamsDialog, Condition.NOT_Installed),
                new ShowDialog(NativeDialogs.MaintenanceTypeDlg, Condition.Installed));

            customUI.On(NativeDialogs.MaintenanceWelcomeDlg, Buttons.Next, new ShowDialog(NativeDialogs.MaintenanceTypeDlg));

            customUI.On(NativeDialogs.MaintenanceTypeDlg, Buttons.Back, new ShowDialog(NativeDialogs.MaintenanceWelcomeDlg));
            //customUI.On(NativeDialogs.MaintenanceTypeDlg, Buttons.Repair, new ShowDialog(NativeDialogs.VerifyReadyDlg));
            customUI.On(NativeDialogs.MaintenanceTypeDlg, Buttons.Remove, new ShowDialog(NativeDialogs.VerifyReadyDlg));

            return customUI;
        }

**Comment by oleg-shilo** [comment] 2020-12-15 13:46
Andrii, it's difficult for me to be effective supporting you with NativeUI questions.

It was quite some time ago when this interface was developed. It works but it was only the first attempt to solve the custom UI challenge.  Today ManagedUI is a preferred approach. 

While both these interfaces have their place and none of them is ideal, ManagedUI is definitelly more powerful and easier to deal with.

I suggest you give it a try and this just might be the solution you are looking for. Create your VS project from the "WixSharp - Custom UI" project template and it will give you full control over your UI appearence and sequence.

If you still prefer to use NativeUI then have a look in the produced wxs file. Most likely the answer will be theer.

**Comment by vinil2001** [comment] 2020-12-15 15:18
Dear Oleg,

Thanks a lot for your suggestion.
I think ManagedUI  this what I need.

**Comment by oleg-shilo** [comment] 2020-12-17 12:36
You are very welcome.

Keep in mind that ManagedUI cannot be displayed if your MSI is bootstrapped with Burn. This limitation is caused by the defect in the Burn v3.* implementation and it is going to be fixed in v4. WiX guys please correct me if I am wrong. The defects prevents any EmbeddedUI from being displayed from the bootstrapper so it is not only WixSharp who is affected.

 But otherwise ManagedUI approach is arguably better from all counts compared to NativeUI you were trying to utilize.

**Closed** 2021-06-23 14:23 UTC
Labels: question
