### ISSUE TITLE
Permenanet Files

### ISSUE THREAD

**Issue by Torchok19081986** [oleg-shilo/wixsharp#50] opened 2017-04-12 07:20 UTC
Hallo Oleg, 

how do i set Files or Folders as permanent ?  i have to  prevent Folders/Files from being delete on uninstall.
I need some Help here.

**Comment by oleg-shilo** [comment] 2017-04-13 11:46
The `Permanent` attribute is a component attribute and because Wix# attitude is to completely hide the component allocation setting its properties/attributes needs to be done via child elements of the component:
```C#
new Dir(@"Docs\Manual",
    new File(@"Files\Docs\Manual.txt").SetComponentPermanent(true),
    new File(@"Files\Docs\help.chm").SetComponentPermanent(true)
```

**Comment by Torchok19081986** [comment] 2017-04-13 12:55
thanks a lot for Help here. 
Is there some possibility set application generated files also as Permanent ? 
During uninstall delete all files, which are not marked as Permanent, also licesense.file and configuration file.

**Comment by oleg-shilo** [comment] 2017-04-16 02:04
>Is there some possibility set application generated files also as Permanent?

You kind of don't need to. On uninstall, MSI runtime never touches and files that it didn't install (e.g. application generated files).

>During uninstall delete all files, which are not marked as Permanent,

This is a bit complicated. You want at runtime to discover if the file as marked as `permanent`, but it is not a mark that can be analyzed as a file attribute. You cannot take a file and tell if it is permanent. This information is saved deep in MSI database and you need to use SQL to extract it. All this huge effort for a very little benefit.

I want to encourage you to review your deployment design. The fact that you need to use `permanent` is already a sign that there might be something wrong with it. 

Why don't you just follow the standard deployment guide line. Install your binaries in the destination. Treat this destination as a "forbidden territory" have only distributable files there. All app generated files (e.g. configs, temps) should go either in the pure app specific or shared folders. Then you don't need to face all these MSI challenges as you do now.

**Comment by Torchok19081986** [comment] 2017-04-17 21:01
thanks for answer. I have to check my buildmsi in Managedproject. Thanks again, 
im new in Wix toolset and Wix Sharp. Do you have some examples for Update application or what is best Practice to update Application ? With versionnumber and Launchcondition like .NET Framework dependence and some another components ?

**Comment by oleg-shilo** [comment] 2017-04-18 00:19
Man! Do I have samples? :)
~95% of Wix# codebase are the samples. If you download the release package you will find the `Samples` folder with ~70 samples for practically all possible deployment scenarios.

You can also dig into Wiki: https://github.com/oleg-shilo/wixsharp/wiki/Deployment-scenarios-upgrades

And as a for the general guideline I always promote this approach: 
* MSI should only be concern about copying and removing the files to the destination. Nothing else. 
* Configuration must be implemented by application. 
* Using non standard UI for MSI is undesirable and almost always is a case of over-engineering.
 
If one doesn't follow even first two points the product will fail "Design for Windows" certification. 

MSI as a deployment framework has such an enormous legacy package that it is totally inappropriate for a modern application development. This is the reason why MS has ditched it and replaced with a new more appropriate deployment solution ClickOnce.

Of course MSI still have it's place: part of bootstrappers, simple CopyX style deployment... but otherwise it is still here for legacy but not for technical reasons.

And Wix# is an attempt to make it easy to use MSI in a more modern way. With minimal development overhead and more adequate programming technologies. But if one wants to use MSI the way it was intended ~15-20 years ago he should prepare for a challenge. And nothing would ease this pain neither WiX nor Wix#.

**Comment by Torchok19081986** [comment] 2017-04-18 07:38
ClickOnce need a publishing place that i dont have and internal VS 2017 Installproject are really not good. They cant do nothing, only installation, thats all. 
Wix Toolset is unclear for me, i have to search some alternative way to create .exe or msi for Install/Update myAppliacation. 
your API is really good and look not complicated as wix toolset as normal. Here i can do setup for myapplications.  unfortunately not all examples works for me. I got errors during install or create msi and some unresolved questions during tests. I have to invest more time to create acceptable setup for myapplications.

**Comment by oleg-shilo** [comment] 2017-04-18 12:17
> ClickOnce need a publishing place that i dont have...

You can use any network shared folder for publishing ClickOnce setup. It's an adequate alternative for the Intranet scenarios. 

>  They cant do nothing, only installation, that's all.

Ironically, this is what I believe any deployment should do. :) 

Anyway, it's ultimately your call and if you believe you need a more complex deployment behavior then go for it. And Wix# is something that can really help you with that.

**Comment by Torchok19081986** [comment] 2017-04-18 15:28
Ok, thanks. With "They cant do nothing, only installation, that's all" i mean that there is no customdialogs and some GUI for it. I try it. Update for my Applications i resolved with Installer Class in Microsoft.Deployment.WindowsInstaller. There is some code needed, but its looks like 

Installer.SetInternalUI(silent);
Installer.ReinstallProduct(MsiRuntime.ProductName, ReinstallModes.FileReplace);
Installer.ConfigureProduct(MsiRuntime.ProductCode, 0, InstallState.Default, null);

Only one codeline dont works fine "Installer.EnableLog(InstallerLogMode.Verbose, MsiRuntime.InstallDir + "\\updatelog.log")". This doesnt create log in InstallDir, but i have some idea why. Probably i need read InstallDir from RegKeyValue, which was created on Install in previously Installation.

**Comment by oleg-shilo** [comment] 2017-04-19 00:32
I cannot comment for the `Installer.EnableLog`, not sure I ever tried it. Though have a look at the Wix# source code and you can find the answer. In the ManagedUI final dialog (Custom UI Sequence VS template) I have a link UI element, which on click opens the setup log file. You can just reuse this solution. 

And just as a side comment, it's arguably not a good idea to have logs in the InstallDir. Particularly if it is `ProgramFiles`. Most likely that ManagedUI solves this problem as well.

**Comment by Torchok19081986** [comment] 2017-04-19 06:28
Thanks. i will search and try it . Thanks for suggestion. Do you know name of sample for Custom UI Sequence ? I dont find VS template . There is only CustomCLR, CustomMSI, EmbededUI, EmbededUI-Wix Issue, EmbededUI - WPF and NuGet_WixSharpCRLDialog. 

Both Logs , Installer.EnableLog and your Log looks alsmost same. Only Installerlog can be set for Debugging or another Level.

**Comment by oleg-shilo** [comment] 2017-04-19 07:25
Templates are part of VS extension: https://marketplace.visualstudio.com/items?itemName=OlegShilo.WixSharpProjectTemplates

Your template is called "WixSharp Managed Setup - Custom UI":
![image](https://cloud.githubusercontent.com/assets/16729806/25167303/4e93fa70-2522-11e7-8b78-54eb3a87aa1f.png)
 
Though I checked the code and I am not setting the custom Log file there. Instead I am reading whole in-memory log content from the session object and then save it in a temp file and open in notepad. 

Now I remember why it's done this way. You cannot enable log to a specific file when MSI is already started. It needs to be done before the start - from the `msiexec.exe` command line. And if your execution was the result of double-clicking.... then tough luck. Nothing you can do about it.

Thus I am not sutre it ios what you are looking for but you can still check the source code for that solution:
![image](https://cloud.githubusercontent.com/assets/16729806/25167970/154c56a6-2525-11e7-8182-17e0901d0b05.png)

**Comment by Torchok19081986** [comment] 2017-04-19 08:28
ok, thanks for explanation again. I created WixSharp Managed Setup and created here WixSharp Managed Setup - Custom Dialog and customize it for my needs. And this was my mistake.
Is there some big difference between WixSharp Managed Setup and WixSharp Managed Setup UI ?

**Comment by oleg-shilo** [comment] 2017-04-19 23:43
Yes there is a difference but not huge. 

In both cases the project type is `ManagedProject` however in case of "Managed Setup - Custom Dialog" the project template includes source code for a dialog that is injected in the Wix# predefined UI dialogs. In case of "Managed Setup - Custom UI" the project template includes source code for the all Wix# predefined UI dialogs that compose the UI sequence.

**Comment by Torchok19081986** [comment] 2017-04-21 07:06
Ok, i understand now. Thanks for explanation. I will use in future only Custom UI project.

**Closed** 2017-04-21 07:06 UTC
Labels: question
