### ISSUE TITLE
[Bug] Multi language installer intermediate .msi not found error

### ISSUE THREAD

**Issue by thenextman** [oleg-shilo/wixsharp#1389] opened 2023-11-30 19:06 UTC
I'm porting an existing Wix3 project to WixSharp. I'm using managed UI and already have my localization (wxl) files.

For a single language, this is working fine:

```
project.Language = "en-US";
project.LocalizationFile = "MyProject_en-us.wxl";
//...
project.BuildMsi();
```

I want to add my French localization, so leaving the original `Language` and `LocalizationFile` set I now do:

```
// project.BuildMsi();
string productMsi = project.BuildMsi();

project.Language = "fr-FR";
string mstFile = project.BuildLanguageTransform(productMsi, "fr-FR", "MyProject_fr-fr.wxl");
productMsi.EmbedTransform(mstFile);
productMsi.SetPackageLanguages("en-US,fr-FR".ToLcidList());
```

And the result is:

> 1>Execute:
> 1>"C:\Program Files (x86)\WiX Toolset v3.11\bin\torch.exe" -p -t language "C:\Users\rmarkiewicz\source\repos\WixSharp Setup1\setup.msi" "C:\Users\rmarkiewicz\source\repos\WixSharp Setup1\fr-FR.msi" -out "C:\Users\rmarkiewicz\source\repos\WixSharp Setup1\fr-FR.mst"
> 1>Windows Installer XML Toolset Transform Builder version 3.11.2.4516
> 1>Copyright (c) .NET Foundation and contributors. All rights reserved.
> 1>
> 1>torch.exe : error TRCH0103: The system cannot find the file 'C:\Users\rmarkiewicz\source\repos\WixSharp Setup1\fr-FR.msi' with type 'Database'.
> 1>
> 1>Unhandled Exception: System.ApplicationException: Error: EmbedTransform.Embed->MsiRecordSetStream
> 1>   at WixSharp.Msi.EmbedTransform.check(MsiError result, String errorContext)
> 1>   at WixSharp.Msi.EmbedTransform.Do(String msi, String mst)
> 1>   at WixSharp_Setup1.Program.Main()

Ok, so it's calling `torch` and passing in the en-US "setup.msi" but also the fr-FR localized "fr-FR.msi", which doesn't exist. Am I supposed to create this manually? I followed the documentation; noting that I don't think `BuildMultilanguageMsi` will work for me (as I have custom localization and need a way to specify the .wxl files to use).

**Comment by oleg-shilo** [comment] 2023-12-01 11:53
No, that localized fr-FR.msi is to be created by the `BuildLanguageTransform`.

I have just updated the sample to be more clear about that:

```C#
        var oneStepTransform = false;
        if (oneStepTransform)
        {
            project.Language = "en-US,uk-UA";
            var msiFile = project.BuildMultilanguageMsi();
        }
        else
        {
            project.Language = "en-US";
            string productMsi = project.BuildMsi();

            project.Language = "uk-UA"; 
            // uk-UA msi will be built (and used to create mst) in the next step
            string mstFile = project.BuildLanguageTransform(productMsi, project.Language);

            productMsi.EmbedTransform(mstFile);
            productMsi.SetPackageLanguages("en-US,uk-UA".ToLcidList());
        }
``` 

Thus you seems to be doing right things simply `BuildLanguageTransform` either fails to build the msi or this msi somehow is not what torch expects.

I suggest you try to see first that your localization works with that multi-step building algorithm. I am speculating that your MyProject_fr-fr.wxl might upset the build. If it works then you can introduce wxl back and see why your fr-FR.msi is failing. 

BTW you may have the answer in the build output. Check it.

If you want to debug, you can just add to your code the local implementation of `BuildLanguageTransform` so you can put a breakppoint there and see waht is going on there. It is fundamentally simple and have no dependency on anything:

```C#
public static string BuildLanguageTransform(this Project project, string originalMsi, string language, string localizationFile = "")
{
    var torch = Compiler.WixLocation.PathCombine("torch.exe");
    var originalLng = project.Language;
    var originalLocalizationFile = project.LocalizationFile;
    try
    {
        project.Language = language;
        project.LocalizationFile = localizationFile;

        string localizedMsi = project.BuildMsi(language).PathGetFullPath();
        string langMst = localizedMsi.PathChangeExtension(".mst");

        new ExternalTool
        {
            ExePath = torch,
            Arguments = $"-p -t language \"{originalMsi}\" \"{localizedMsi}\" -out \"{langMst}\""
        }
        .ConsoleRun();
            
        return langMst;
    }
    finally
    {
        project.LocalizationFile = originalLocalizationFile;
        project.Language = originalLng;
    }
}
```

**Comment by thenextman** [comment] 2023-12-01 18:44
Thank you. I'm going to look at this more closely and I'll come back with my findings.

Side note: building with WiX, I can add custom UI and insert only the localizations for my custom UI in the wxl.

It seems like with WixSharp, as soon as I add a wxl for my main language, the default localizations are lost (I only see the placeholders in my UI).

Of course, I can get them back by copying them out of the WiX source code into my custom wxl, but I'm just wondering why this is necessary?

**Comment by thenextman** [comment] 2023-12-02 01:50
Hello

Thanks for the information. With regard to my issue around application of the wxl file, I'll create a new issue as I don't want to complicate things here.

I've tried simplifying things but I'm not getting anywhere. I'm running Visual Studio 2022, using the "WixSharp Managed Setup - Custom UI (Wix3)" template. I installed the extension a few days ago so assume I'm at the latest version.

If I create a new project on that template and simply change the `project.BuildMsi()` to:

```
// One step transform, no other customization
project.Language = "en-US,fr-FR";
project.BuildMultilanguageMsi();
```

The project fails to build:

> 1>C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\MyProduct.wxs(32): error LGHT0103: The system cannot find the file 'MyProduct.wxl'.
> 1>C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\MyProduct.wxs(33): error LGHT0103: The system cannot find the file 'MyProduct.licence.rtf'.
> 1>C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\MyProduct.wxs(34): error LGHT0103: The system cannot find the file 'MyProduct.dialog_bmp.png'.
> 1>C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\MyProduct.wxs(35): error LGHT0103: The system cannot find the file 'MyProduct.dialog_banner.png'.
> 1>Execute:
> 1>"C:\Program Files (x86)\WiX Toolset v3.11\bin\torch.exe" -p -t language "C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\MyProduct.msi" "C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\fr-FR.msi" -out "C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\fr-FR.mst"
> 1>Windows Installer XML Toolset Transform Builder version 3.11.2.4516
> 1>Copyright (c) .NET Foundation and contributors. All rights reserved.
> 1>
> 1>torch.exe : error TRCH0103: The system cannot find the file 'C:\Users\rmarkiewicz\Desktop\WixSharp Setup1\fr-FR.msi' with type 'Database'.
> 1>
> 1>Unhandled Exception: System.ApplicationException: Error: EmbedTransform.Embed->MsiRecordSetStream
> 1>   at WixSharp.Msi.EmbedTransform.check(MsiError result, String errorContext)
> 1>   at WixSharp.Msi.EmbedTransform.Do(String msi, String mst)
> 1>   at WixSharp.LocalizationExtensions.BuildMultilanguageMsi(Project project, String path)
> 1>   at WixSharp_Setup1.Program.Main()

Multi step transform gives the same result.

So; this does appear to either be a bug or a problem in my environment. To be clear - I tested using a brand new project with no other changes.

**Comment by oleg-shilo** [comment] 2023-12-02 07:59
It is a WixSharp bug. I can reproduce it.

I am afraid some recent changes in the building algorithm got nasty side effect when temp files are deleted presumably too early.
I am not sure if it is a template or an engine problem. Interestingly enough during the build test does not fail for a very similar project. This is my speculation. Will investigate it.

**Comment by oleg-shilo** [comment] 2023-12-02 11:58
Indeed it was the defect that is caused by the combination of the ManagedUI and the fact that one project is compiled twice (`BuildLanguageTransform`). It is the scenario that was not handled properly.

The defect is fixed now and the fix will be available in the very next release.

**Comment by oleg-shilo** [comment] 2023-12-02 12:19
BTW the difference between your earlier (unsuccessful) attempt to use `BuildLanguageTransform` and mine (successful) was caused by the fact that I used native UI and you did ManagedUI. 

When I changed my test to ManagedUI I got the same problem.

**Comment by oleg-shilo** [comment] 2023-12-03 02:06
I will try to do the release in a day or two

**Closed** 2024-02-07 21:08 UTC
Labels: bug, Done / Released
