### ISSUE TITLE
Compiler.BuildMsi errors out when ran in Release mode (if CustomActions are added)

### ISSUE THREAD

**Issue by ERGeorgiev** [oleg-shilo/wixsharp#1449] opened 2024-02-11 16:31 UTC
The following works in DEBUG but not in RELEASE:
```
    [CustomAction]
    public static ActionResult Test(Session session)
    {
        return ActionResult.Success;
    }

    public void Setup()
    {
        var testProject = new Project()
        {
            UI = WUI.WixUI_ProgressOnly,
            Name = "CustomActionTest"
        };
        var test = new ManagedAction(
            Test, Return.check, When.After, Step.InstallFinalize, Condition.NOT_Installed);
        testProject.AddAction(test);
        Compiler.BuildMsi(testProject);
    }
```

The error thrown is `cannot package managedca assembly %this%`

Also note, if the custom action is declared locally like so:
```
        var testProject = new Project()
        {
            UI = WUI.WixUI_ProgressOnly,
            Name = "CustomActionTest",
            Actions = new[] { new ManagedAction(Test) }
        };
        testProject.BuildMsi();

        [CustomAction]
        static ActionResult Test(Session session)
        {
            return ActionResult.Success;
        }
        return;
```

Then it does not work. It throws a confusing error "illegal characters in path".

**Comment by ERGeorgiev** [comment] 2024-02-11 16:32
Note: project.BuildMsi works as intended.

**Comment by oleg-shilo** [comment] 2024-02-11 23:21
> The following works in DEBUG but not in RELEASE:
Not sure about your runtime settings (e.g. current dir) but I cannot reproduce the problem. I have committed your very sample and it works for me in both Release and Debug.

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/6c6dd36f-6074-49b0-b9f1-40f512d19c4f)

> Also note, if the custom action is declared locally like so:

The code you provided has a syntax error. Probably typo. But anyway you have to have a proper top-level class as it demonstrated in the samples. It is WiX requirement, not the WixSharp one. 

The easiest way to avoid problems like the ones that you are facing is to create your project from the WixSharp VS project temple. It will ensure that all building plumbing is set correctly.

And about the CA. I highly recommend to migrate to is ManagedProject and use events (wrapped CA) instead raw CA: https://github.com/oleg-shilo/wixsharp/wiki/Managed-Setup-Model#event-driven-custom-actions

The code is cleaner, the `AfterInstall` event is elevated, and it's just a way more maintainable:

```C#
project.BeforeInstall += args =>
{
    if (!args.IsUninstalling)
        Tasks.StopService("some_service", throwOnError: false);
};

project.AfterInstall += args =>
{
    if (!args.IsUninstalling)
        Tasks.StartService("some_service", throwOnError: false);
};
```

**Comment by ERGeorgiev** [comment] 2024-02-12 17:46
That does look great. I saw other examples of the project.BeforeInstall and was wondering why I lack the capability, I assumed it was from an older version.

**Comment by oleg-shilo** [comment] 2024-02-12 23:32
Yes, it could be because of the older version or because of the use of `Project` instead of `ManagedProject`:

```C#

// offers simplified access to all WiX features (e.g. CA)
var project = new Project(...) 

// the same as Project, plus pure WixSharp features (e.g. fully custom Managed UI, 
// more advanced version of CA - runtime events)
var project = new ManagedProject(...) 
```

**Closed** 2024-05-01 12:19 UTC
Labels: discussion
