### ISSUE TITLE
Can't install dll to windows/system32

### ISSUE THREAD

**Issue by yfnfif** [oleg-shilo/wixsharp#45] opened 2017-03-27 06:57 UTC
Hello, Oleg!
I want to install MyLibrary.dll to windows/system32. After installation there isn't MyLibrary.dll in windows/system32.
My code:
```
var project = new Project("MyProduct",
            new Dir(@"%SystemFolder%", new File("MyLibrary.dll")));
```

Output msi:
```
<Directory Id = "TARGETDIR" Name="SourceDir">
    <Directory Id = "INSTALLDIR" Name="%SystemFolder%">
    <Component Id = "Component.MyLibrary.dll" Guid="107476c8-8665-4b14-a6bd-008f39ec5786">
        <File Id = "MyLibrary.dll" Source="MyLibrary.dll" />
    </Component>
    </Directory>
</Directory>
```

%SystemFolder% isn't Wix environment constant.
I have the same problem with Assembly.

Installing in "%SystemFolder%/TestFolder" is OK.

**Comment by oleg-shilo** [comment] 2017-03-28 02:26
Yes it seems to be broken for cases without sub-folders. Use direct WiX constants instead:
```C#
var project = new Project("MyProduct",
            new Dir("SystemFolder", new File("MyLibrary.dll")));
```

**Comment by yfnfif** [comment] 2017-03-28 08:14
I don't know why, but your sample doesn't install MyLibrary.dll in system32.
The code below works well: 
```
var project = new Project("MyProduct",
            new Dir(new Id("SystemFolder"), "System", new File("MyLibrary.dll")));
```

**Comment by oleg-shilo** [comment] 2017-03-28 08:24
My bad, I forgot, it's not the name it's `Id` that controls the destination path for the WiX constants for spacial folders.

Your work around is exactly what is needed.

**Comment by oleg-shilo** [comment] 2017-03-28 11:36
The problem is caused by the auto-assignment `INSTALLDIR` id to the bottom-most directory, which is in your case happens to be a special folder that needs to keep its original Id.

Thus the alternative work around to set the auto-id value to the string of your choice:
```C#
Compiler.AutoGeneration.InstallDirDefaultId = "SystemFolder";
```

**Comment by oleg-shilo** [comment] 2017-04-04 11:41
As an enhancement added compile warning on special folder dirId reassignment.

**Closed** 2017-05-02 02:10 UTC
Labels: Done, enhancement

**Comment by siongyuen** [comment] 2020-05-28 12:01
> The problem is caused by the auto-assignment `INSTALLDIR` id to the bottom-most directory, which is in your case happens to be a special folder that needs to keep its original Id.
> 
> Thus the alternative work around to set the auto-id value to the string of your choice:
> 
> ```cs
> Compiler.AutoGeneration.InstallDirDefaultId = "SystemFolder";
> ```

I was trying so hard to create subfolder under the SystemFolder and keep getting duplicate id until I found this as suggested by the owner.
Compiler.AutoGeneration.InstallDirDefaultId = "SystemFolder";
