### ISSUE TITLE
regarding this question:  https://wixsharp.codeplex.com/discussions/663144

### ISSUE THREAD

**Issue by rachelleP** [oleg-shilo/wixsharp#83] opened 2017-06-08 06:01 UTC
I understand that codePlex is not supported any more- so moved the question here.
 https://wixsharp.codeplex.com/discussions/663144

**Comment by oleg-shilo** [comment] 2017-06-08 13:12
The binaries (assemblies) included as the result of adding CAs supposed to be optimized. Thus the same file to be included only once even if it is used by multiple CAs. 

This means that the problem is caused by either older version of Wix# or by flaw in the optimization algorithm. 

Please  provide a sample (hello-world style) project that demonstrates the problem so it can be investigated.

**Comment by rachelleP** [comment] 2017-06-11 13:48
We are using Wix# 1.0.7 , does the problem exists there? is there a workaround?

**Comment by oleg-shilo** [comment] 2017-06-12 11:36
> We are using Wix# 1.0.7 , does the problem exists there?

I don't know. It's hard for me to say when the CA assembly inclusion optimization was implemented. The latest release has it so you can test it and tell me if the problem is there.  

> is there a workaround?

I am not sure that there is a problem, so I cannot advice any work around. That's why I asked you to provide the test case so I can investigate it.   

____

My previous post has explained the situation. The feature (CA assembly inclusion optimization) is implemented. If it's broken then please provide the test case so I can start working on it. 

If your code works in the current release but not in the old one then of course the only appropriate course of actions is to update your WixSharp to the latest version.

**Comment by rachelleP** [comment] 2017-06-14 07:47
I tried the latest release of Wix# and it solved the problem. I guess I should update my installer to the latest version. The latest version is without backwards capability, right? Was is the best way to update the installer with the latest Wix# release?

**Comment by oleg-shilo** [comment] 2017-06-14 12:10
> The latest version is without backwards capability, right? 

No, it is backwards compatible. You can feed the C# old code into the new Wix# compiler.

> Was is the best way to update the installer with the latest Wix# release?

Use NuGet to get (update to) the latest release. This is the recommended approach.

Cheers.

**Comment by rachelleP** [comment] 2017-06-15 07:26
For some reason, to me is seem not backwards compatible, as when I update my wix# the following are unknown: 
For Project: Comments, Manufacturer, AddRemoveProgramsIcon and ProductIcon.
In addition also project.Media.Attributes["EmbedCab"] is unknown.
Any idea what to use instead?

**Comment by rachelleP** [comment] 2017-06-15 07:40
In addition, I discovered that I have a lot more issues, for example: project.ResolveWildCards(); isn't working and more...

**Comment by rachelleP** [comment] 2017-06-15 08:52
And what about the .wxs file, is it different now?

**Comment by oleg-shilo** [comment] 2017-06-15 23:58
You are right there are some changes in API that require minor adjustments of old code. Though these changes are caused by the reallocation of the API points but not the fundamental changes in API itself. 

OK, will answer now your questions one by one.
>For Project: Comments, Manufacturer, AddRemoveProgramsIcon and ProductIcon

Yes this the one that has been moved to the new locations because of the new features that couldn't fit to the old API "parent". Have a look at '_ProductInfo_' sample it has it all covered.

> In addition also project.Media.Attributes["EmbedCab"] is unknown. 

If you have a look at the signature you will see that `project.Media` is a list now (to allow multiple Media items). You will need to access it via `project.Media[0]`.

>...project.ResolveWildCards(); isn't working ...

This doesn't tell me much. Please elaborate. And also have a look at '_WildCard Files_' sample.

>And what about the .wxs file, is it different now?

I am not sure I follow this one. An wxs file is a by-product of MSI authoring with Wix#. In fact its generation even disabled by default. It may or may not be emitted differently between the versions. It's kind of irrelevant. Does your case produce the correct MSI? This is what matters after all.

**Comment by rachelleP** [comment] 2017-06-16 08:02
Thanks! I kind of solved must of the problems, but still have a few problems, not sure what there are yet. 
If i'll have more question, I'll let you know ;)
Thanks again...

**Comment by oleg-shilo** [comment] 2017-06-17 10:35
I am closing the issue for now and you can reopen it if you have more questions.

**Comment by rachelleP** [comment] 2017-06-18 13:16
I hope the last question ;)
What about "CompanionFile"? For some reason, when trying to add this attribute, the Compiler.BuildMsi is returning null. Any suggestion?

**Comment by oleg-shilo** [comment] 2017-06-18 13:18
How do you add this attribute? Can you provide a code snippet?

**Comment by rachelleP** [comment] 2017-06-18 13:27
MyFiles.Files = MyFiles.Files.Add(new WixSharp.File(MyFeature, Path.GetFileName(file))
                {   
                    Attributes = new Attributes { { "DiskId", "2" }, { "Compressed", "no" }, { "KeyPath", "no" },  { "CompanionFile", "File.mySvc.exe" }},
					Condition = new Condition(osCondition)
                 });

**Comment by oleg-shilo** [comment] 2017-06-19 02:11
It must be something with your declarations in the rest of the code. I just checked the "Install Files" sample and your attribute gets injected just fine. For both `Attributes` and `AttributesDefinition`:

![image](https://user-images.githubusercontent.com/16729806/27266956-649e39d4-54e8-11e7-8786-5c349f691714.png)

**Comment by rachelleP** [comment] 2017-06-20 13:15
I discovered that my problem is that I run my installer in a few languages (the same code runs the different languages one after the other). I can see that every language that's running is adding a number at the end of the file name, like this:
the first language that runs - Component.mySvc.exe
the second language - Component.mySvc.exe.1
the third - Component.mySvc.exe.2
and so on...
That is why from all languages, except for the first one, cannot compile, as Component.mySvc.exe doesn't exist by them.
Any idea how to best solve the problem? this will also cause a problem when compiling all of the msi of all languages into one msi, wouldn't it?
When compiling all languages into one .msi using torch, are there more problems expected regarding the wix# upgrade?

**Comment by oleg-shilo** [comment] 2017-06-21 02:13
I am not sure about the details as I have no idea of what you are doing and how your setup is structured. So far you didn't share a single code sample :)

I cannot be productive unless I can understand the problem. And in your case a simple hello-world style sample that shows the problem is the best approach to proceed.

**Comment by rachelleP** [comment] 2017-06-21 16:14
Attached is a sample: 
[InstallerSample.zip](https://github.com/oleg-shilo/wixsharp/files/1092138/InstallerSample.zip)

As it can be seen in the .wxs file, at the first component in the directory, a number is added at the end of the Id of "mySvc" and then when looking for it for adding it as Companion file - it doesn't exist, as we are looking for the component without the number at the end... (the first language - en, is working correctly, because it's the first language that runs, so the numbers are not added).
It's not only the technical problem of the number, to my opinion, because numbers are added to all components' Id, this might cause a lot more problems when compiling all languages into one .msi (using torch), am I wrong?
Any idea how to solve this problem - or any idea how to force that there wouldn't be a number added to the Id of the different components?

**Comment by oleg-shilo** [comment] 2017-06-22 04:13
Excellent. Thank you for such a good test project. Now I can see the problem in details. 

The Id rollover like in your case is expected and if not desired can be avoided by setting the Ids explicitly. Though this approach ins not applicable for you as you do not create `File` by yourself but rather automatically resolve if from the wild-card path definitions. 

In such case you supposed to use an alternative approach: resetting the Id generator between the builds:
```C#
WixEntity.DoNotResetIdGenerator = false;
```
But unfortunately (I just found out) DoNotResetIdGenerator is broken. I have created the Issue #90 and it will be fixed soon.

Until the fix is available you can use one of these two workarounds:
XML:
```c#
static void WixSharpPatches(XDocument document)
{
    //Adding additional media for external files (driver files and MSI)
    document.Root.Select("Product").AddElement("Media", "Id=2");
    document.Root.FindAll("File")
                 .Where(x => x.HasAttribute("Id", a => a.StartsWith("mySvc.exe")))
                 .ForEach(x => x.SetAttribute("Id", "mySvc.exe"));
}
``` 

Reflection:
```
static void ResetIds()
{
    var ids = (IList)typeof(WixEntity).GetField("alreadyTakenIds", .BindingFlags.NonPublic | BindingFlags.Static)
                                      .GetValue(null);

    var idMap = (IDictionary)typeof(WixEntity).GetField("idMaps", BindingFlags.NonPublic | BindingFlags.Static)
                                              .GetValue(null);
    ids.Clear();
    idMap.Clear();
}
...
static void WixSharpPatches(XDocument document)
{
    //Adding additional media for external files (driver files and MSI)
    document.Root.Select("Product").AddElement("Media", "Id=2");
    ResetIds();
}
```
I have attached the solution code.

----
BTW, you can use `AttributesDefinition` instead `Attributes`. The same outcome though slightly more readable code. Though it's a matter of personal taste :)
```C#
Package = new Package
{
    AttributesDefinition = @"InstallerVersion = 200;
                             InstallScope     = perMachine;
                             Languages        = 1033,1031,1034,1036"
},
```




[Setup.zip](https://github.com/oleg-shilo/wixsharp/files/1093606/Setup.zip)

**Comment by rachelleP** [comment] 2017-06-25 11:50
If I may ask, when is the fix expected to be released?

**Comment by rachelleP** [comment] 2017-06-25 11:50
Thanks for the detailed answer ;)

**Comment by oleg-shilo** [comment] 2017-06-26 04:35
It is released now: https://github.com/oleg-shilo/wixsharp/releases/tag/v1.4.6.0

**Comment by rachelleP** [comment] 2017-06-26 05:19
Wow! thanks!!!

**Closed** 2017-08-02 03:43 UTC
Labels: bug, Done, question

**Comment by rachelleP** [comment] 2017-08-30 07:19
Regarding the above question (on Jun 15).
For adding the Comments to the project, If adding it under ControlPanelInfo, it wouldn't appear when right clicking the .msi file, under details. Is there a different way to add it?

**Comment by rachelleP** [comment] 2017-08-30 07:52
I was able to fix that by adding an Attribute "Comments" to the package.
