### ISSUE TITLE
Wix4: wix.exe not found if installed as local tool

### ISSUE THREAD

**Issue by FerdinandBrunauer** [oleg-shilo/wixsharp#1444] opened 2024-02-05 15:28 UTC
In .NET it is possible to install local tools. If `wix` is installed as such, WixSharp is not detecting it and the build fails.

This is especially useful if tools are used in the build pipeline because e.g.:
- Used versions are version controlled and fixed
- Builds do not interfere with parallel running builds (An update of a tool might cancel the parallel build)

How to reproduce:
- Create a new project with `dotnet new`
- Create a tool manifest with `dotnet new tool-manifest`
- Install the wix as local tool with `dotnet tool install wix`. This will create a manifest like:
```
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "wix": {
      "version": "4.0.3",
      "commands": [
        "wix"
      ]
    }
  }
}
```
- Ensure that wix is working by using `dotnet wix -h`. This will produce the default help output of the wix tool.

Proposed solution:
- Invoke `wix` by using `dotnet tool wix`. This will use the installed local tool OR as fallback the global installation.
- Remove the explicit check for `wix.exe`

If you agree with the proposed solution, I would be willing to create a small PR for it.

**Comment by oleg-shilo** [comment] 2024-02-07 07:43
I think it will be possible.
Changing this issue into "proposal"

**Comment by oleg-shilo** [comment] 2024-02-11 11:29
Done, will be available in the very next release (this week)

**Comment by goldsam** [comment] 2024-03-14 04:49
This is broken in both 2.1.2 and 2.1.3. `ExternalTool.Locate` is being invoked such that the `file` argument has the value `"localtool:wix"`. The conditional fragment on line 2089 will never be true and thus the full condition is never true. The logic after the if evaluates to null since no executable exists named `"localtool:wix"`. 

https://github.com/oleg-shilo/wixsharp/blob/24713a879286b345c22198e654189f8b17dc1c51/Source/src/WixSharp/CommonTasks.cs#L2087-L2105

The code later blows up inside `Compiler.Run` on line 3525 with a `NullReferenceException` since `file` is null:

https://github.com/oleg-shilo/wixsharp/blob/cfc92ccddfb2c7c8070221d99b77af42bbe78b8e/Source/src/WixSharp/Compiler.cs#L3517-L3528

Also, I noticed that there is a major regression from [`CommonTasks.cs` in the 2.1.2 branch](https://github.com/oleg-shilo/wixsharp/blob/v2.1.2.0/Source/src/WixSharp/CommonTasks.cs) to [the 2.1.3 branch](https://github.com/oleg-shilo/wixsharp/blob/v2.1.3.0/Source/src/WixSharp/CommonTasks.cs) in the repo, It seems like the 2.1.3 branch is pointing to a much older commit. This regression does not seem to be reflected in the published nuget package on nuget.org.

**Comment by oleg-shilo** [comment] 2024-03-18 01:24
I am not sure I follow your explanation.

> The conditional fragment on line 2089 will never be true....

Correct. It's an intention for the local tool scenario.

> The code later blows up inside Compiler.Run on line 3525 with a NullReferenceException since file is null:

I cannot see it. `file` is always a non-empty string. In  case of local tool it is `"localtool:wix"`. Thus there is something in your case that triggered an alternative execution flow that I cannot reproduce.

Why don't we stepback and see what problem is?
I have attached the working solution that successfully builds with local wix installation:

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/d1dd7f16-5a5b-48db-accd-54271cffc7f7)

Why don't you test it in your environment to see if it behaves the same way as in mine.
 
[WixSharp Setup13.zip](https://github.com/oleg-shilo/wixsharp/files/14629761/WixSharp.Setup13.zip)

As for branches, I had a hiccup with the branches, so possible made a mistake during the release with the tags. Maintaining two streams WiX3 and WiX4 comes with the cost :o(
Thus please use the latest `wix-v4-master`.

**Comment by goldsam** [comment] 2024-03-18 14:13
I completely failed to mention I was using the `WixSharp.Core` package. I made the faulty assumption that this was the focus of this discussion due to use of dotnet tooling. The example project you provided uses net472. Is that intentional?

**Comment by oleg-shilo** [comment] 2024-03-19 07:22
Great, txs. I can reproduce it now

**Comment by oleg-shilo** [comment] 2024-03-19 08:18
Done. Released as a hot fix package:

```txt
dotnet add package WixSharp.Core --version 2.1.4-hotfix
```

It was a nasty problem caused by the differences in the implementation of `IO.Path.GetFileNameWithoutExtension()` on .NET vs .NET-Core.

```C#
// .NET Framework
var file = IO.Path.GetFileNameWithoutExtension("localtool:wix"); // returns "wix"

// .NET Core
var file = IO.Path.GetFileNameWithoutExtension("localtool:wix"); // returns "localtool:wix"
```

I have updated the algorithm to be runtime-neutral. And in fact more accurate:

```C#
public static string Locate(string file)
{
    if (file.StartsWith("localtool:")) // there is no need to locate it as it will be invoked with `dotnet` launcher
        return file;

    if (file.PathGetFileNameWithoutExtension() == "wix" &&
        file.PathGetDirName().IsEmpty() &&
        IsLocalTool("wix")) // currently we expect only wix.exe to be a local tool
    . . .
```

```

**Comment by goldsam** [comment] 2024-03-20 13:53
That fixed it! Please note that you did not release a corresponding `WixSharp.Msi.Core` at version 2.1.4-hotfix, so I had to do some finagling with my `PackageReference`s. Thanks for addressing this 😊

**Comment by oleg-shilo** [comment] 2024-03-20 14:46
Sorry, my bad. 

The intent was to only release WixSharp.Msi as a hot fix as there are no changes in `WixSharp.Msi.Core`. 

But because the package dependencies are automatically generated based on asm references the nuspec unintentionally got dependency on the bumped version of `WixSharp.Msi.Core` that does not exist. It was my mistake.

Since the fix is no verified I just republished it as a proper v2.1.4 release for both packages.|
 So you can update your packages now.

**Closed** 2024-05-01 12:19 UTC
Labels: bug, enhancement, Done / Released
